---

version: 2
log-file: /tmp/efm.log
log-level: 10

tools:
  vim-vint: &vim-vint
    lint-command: "vint -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  misspell: &misspell
    lint-command: "misspell"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  eslint_d: &eslint_d
    lint-command: 'eslint_d -f unix --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    lint-ignore-exit-code: true
    format-command: 'eslint_d --fix-to-stdout --stdin --stdin-filename=${INPUT}'
    format-stdin: true

  prettier: &prettier
    lint-command: "npx prettier"
    format-command: "npx prettier"

  golint: &golint
    lint-command: "golint"
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %m"

  goimports: &goimports
    format-command: "goimports"
    format-stdin: true

  black: &black
    format-command: "black -"
    format-stdin: true

  isort: &isort
    format-command: "isort --stdout -"
    format-stdin: true

  flake8: &flake8
    lint-command: "flake8 --max-line-length 160 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  terraform: &terraform
    format-command: "terraform fmt -"
    format-stdin: true

  luafmt: &luafmt
    format-command: "luafmt --stdin"
    format-stdin: true

  shellcheck: &shellcheck
    lint-command: "shellcheck -f gcc -x -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  vim:
    - <<: *vim-vint
    - <<: *misspell
  javascript:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *misspell
  typescript:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *misspell
  javascriptreact:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *misspell
  typescriptreact:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *misspell
  yaml:
    - <<: *yaml-yamllint
    - <<: *prettier
    - <<: *misspell
  json:
    - <<: *prettier
    - <<: *misspell
  html:
    - <<: *prettier
    - <<: *misspell
  scss:
    - <<: *prettier
    - <<: *misspell
  css:
    - <<: *prettier
    - <<: *misspell
  markdown:
    - <<: *prettier
    - <<: *misspell
  go:
    - <<: *goimports
    - <<: *golint
    - <<: *misspell
  python:
    - <<: *black
    - <<: *isort
    - <<: *flake8
    - <<: *misspell
  tf:
    - <<: *terraform
    - <<: *misspell
  lua:
    - <<: *luafmt
    - <<: *misspell
  sh:
    - <<: *shellcheck
    - <<: *misspell
  pandoc:
    - <<: *prettier
    - <<: *misspell
